### ISSUE TITLE
Hacer tablero de visión del producto

### ISSUE THREAD

**Issue by JorgeGrisales** [MarianaHerreraVelasquez/equipo5_gaa_ppi2020#3]
![](https://i.ibb.co/K9Vgw2v/Whats-App-Image-2020-07-01-at-9-08-34-PM.jpg)

**Comment by marthaduque** [comment]
En la visión debe ir el nombre del proyecto y en las columnas de caracteristicas y beneficios deben ser mas puntuales teniendo en cuenta el alcance de su proyecto
