### ISSUE TITLE
Identificar y describir los interesados

### ISSUE THREAD

**Issue by JorgeGrisales** [MarianaHerreraVelasquez/equipo5_gaa_ppi2020#4]
•Personas que usaran el sistema

Usuarios: Los clientes que acuden al uso del sistema experimentaran una mayor comodidad al momento de hacer el pedido.
Administradores del sistema: Encargados del correcto funcionamiento del sistema, brindando ejecución, mantenimiento, operación y seguro del aplicativo web. (Los meseros, administradores, operadores, despachadores, gerentes del restaurante).

•Personas interesadas en el sistema: 

Usuario: Los principales actores para uso del sistema.
Gerencia: Propietarios de los restaurantes.
Competencia: Los posibles usuarios de los aplicativos.

•Entidades:

Gubernamentales: Son las que marcan la norma.
Instituciones: Los que regulan la norma.
Comités: Los que vigilan que las normas
Áreas: Las que cumplen la norma.

**Comment by marthaduque** [comment]
Falta adicionar la identificación de interesados
