### ISSUE TITLE
Realizar diagrama de Espina de Pescado

### ISSUE THREAD

**Issue by JorgeGrisales** [MarianaHerreraVelasquez/equipo5_gaa_ppi2020#6]
![image](https://user-images.githubusercontent.com/66391454/85067822-ee455580-b176-11ea-8545-894fc196db44.png)

**Comment by AngelIshimura** [comment]
<img src="Imagen.jpg">

**Comment by MiguelATamayo** [comment]
<img src="https://pbs.twimg.com/media/EAkvUSkXoAAcgA-?format=jpg&name=small">

**Comment by marthaduque** [comment]
Llevar la documentación a la wiki

**Comment by marthaduque** [comment]
en el diagrama en la cabeza del pescado debe quedar claro que es en la toma del pedido
